language: node_js
node_js:
  - "6.0"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - gulp build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
